import{a as c}from"./assets/vendor-a61d8330.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(r){if(r.ep)return;r.ep=!0;const n=o(r);fetch(r.href,n)}})();const i="live_UGW28AStEXxXBnOyH0oD3YCLDHdMg5nMeESQkDaE6DyekcykOafpXUvOzyDJBoXg";c.defaults.headers.common["x-api-key"]=i;function y(){return c.get("https://api.thecatapi.com/v1/breeds").then(t=>t.data).catch(t=>console.error("An error occurred:",t.message))}function p(t){const s=`https://api.thecatapi.com/v1/images/search?breed_ids=${t}`;return c.get(s).then(o=>o.data[0]).catch(o=>{console.error("An error occurred:",o.message)})}const e={breedSelect:document.querySelector(".breed-select"),loader:document.querySelector(".loader"),errorMessage:document.querySelector(".error"),catInfo:document.querySelector(".cat-info")};e.loader.style.display="none";e.errorMessage.style.display="none";function u(t){return`
    <div class="cat-card">
      <img class="cat-image" src="${t.url}" alt="Cat Image">
      <div class="cat-details">
        <h2 class="cat-name">${t.breeds[0].name}</h2>
        <p class="cat-description">${t.breeds[0].description}</p>
        <p class="cat-temperament">Temperament: ${t.breeds[0].temperament}</p>
      </div>
    </div>
  `}function f(t){e.catInfo.innerHTML=u(t),e.loader.style.display="none",e.catInfo.style.display="block",e.breedSelect.style.display="block"}function d(){e.loader.style.display="none",e.breedSelect.style.display="none",e.catInfo.style.display="none",e.errorMessage.style.display="block"}function m(t){const s=t.target.value;e.loader.style.display="block",e.breedSelect.style.display="none",e.catInfo.style.display="none",p(s).then(o=>{f(o),e.errorMessage.style.display="none"}).catch(o=>{d(),console.error("Error fetching cat info:",o)})}function h(){e.loader.style.display="block",e.breedSelect.style.display="none",e.catInfo.style.display="none",y().then(t=>{console.log("Fetched Breeds:",t),t.forEach(s=>{const o=document.createElement("option");o.value=s.id,o.textContent=s.name,e.breedSelect.appendChild(o)}),e.breedSelect.addEventListener("change",m),e.loader.style.display="none",e.breedSelect.style.display="block"}).catch(t=>{console.error("Error fetching breeds:",t),d()})}h();
//# sourceMappingURL=commonHelpers.js.map
